# __Demo: Transformer Applications__

# __Context:__

The text below includes two sections, text1 and text2. `text1` presents a customer's negative review of the iPhone, while `text2` provides a positive review. This demo aims to demonstrate the Transformer models' ability to manage two distinct tasks effectively.

In [1]:
text1 = '''Extremely disappointed with my recent iPhone purchase from Apple. The device constantly lags, and the battery life is abysmal,
barely lasting through the day. Despite the hefty price tag, the performance is far from satisfactory. Customer support has been unhelpful,
providing no viable solutions to address these persistant issues. This experience has left me regretting my decision to choose Apple,
and I expected much better from a company known for its premium products.'''

text2 = '''I recently purchased an iPhone from Apple, and it has been an absolute delight! The device runs smoothly, and the battery life is impressive, easily lasting throughout the day.
The price, though high, is justified by the excellent performance and top-notch customer support. I am thoroughly satisfied with my decision to choose Apple, and it reaffirms their reputation
for delivering premium products. Highly recommended for anyone seeking a reliable and high-performance smartphone'''

# __Task 1: Text Classification__
- Analyze customer reviews of an iPhone purchase to classify the sentiment as positive or negative.

In [5]:
#pip install tf-keras

In [ ]:
from transformers import pipeline
classifier = pipeline("text-classification") 
result1 = classifier(text1)
result2 = classifier(text2)
print("Text 1 Sentiment:", result1)
print("Text 2 Sentiment:", result2)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

WARNING:tensorflow:From c:\Users\Lenovo\anaconda3\envs\agentvenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cpu

Text 1 Sentiment: [{'label': 'NEGATIVE', 'score': 0.9997414946556091}]
Text 2 Sentiment: [{'label': 'POSITIVE', 'score': 0.9998181462287903}]

In [ ]:
# why classifier = pipeline("text-classification") is for senement analysis?
# The line classifier = pipeline("text-classification") initializes a text classification pipeline using the Hugging Face Transformers library.
# Text classification is a common natural language processing (NLP) task that involves categorizing text into predefined classes or labels.
# Sentiment analysis is a specific type of text classification where the goal is to determine the sentiment expressed in a piece of text, typically categorizing it as positive, negative, or neutral.
# By using pipeline("text-classification"), the code sets up a model that can analyze the sentiment of the provided text inputs (text1 and text2) and classify them accordingly.

In [7]:
from transformers import pipeline
#text classification
classifier = pipeline("text-classification")
import pandas as pd

# Analyze for text1
outputs1 = classifier(text1)
pd.DataFrame(outputs1)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

      label     score
0  NEGATIVE  0.999741

In [8]:
#!pip install transformers -U

__Note:__ The output displays a label with its corresponding probability.

In [9]:
#Ananlyze for text2:
outputs2 = classifier(text2)
pd.DataFrame(outputs2)

      label     score
0  POSITIVE  0.999818

# __Task 2: Text Generation__

- Generate a customer service response to one of the reviews. This is achieved by using a text generation pipeline.

In [10]:
from transformers import set_seed
set_seed(42) # Set the seed to get reproducible results

generator = pipeline("text-generation")
response = "Dear Patron, Thanks for writing in! I am sorry to hear your experience with us."
prompt = text1 + "\n\nCustomer service response:\n" + response
outputs = generator(prompt, max_length=150)
print(outputs[0]['generated_text'])

No model was supplied, defaulted to openai-community/gpt2 and revision 607a30d (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

c:\Users\Lenovo\anaconda3\envs\agentvenv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lenovo\.cache\huggingface\hub\models--openai-community--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cpu
Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

Extremely disappointed with my recent iPhone purchase from Apple. The device constantly lags, and the battery life is abysmal,
barely lasting through the day. Despite the hefty price tag, the performance is far from satisfactory. Customer support has been unhelpful,
providing no viable solutions to address these persistant issues. This experience has left me regretting my decision to choose Apple,
and I expected much better from a company known for its premium products.

Customer service response:
Dear Patron, Thanks for writing in! I am sorry to hear your experience with us. We have had some frustrating experiences with customer service across the board, and as with any good customer service company, there are some common problems such as

__Note:__ This demonstrates how Transformers can create context-aware responses, which can be a valuable tool in automated customer service or similar applications.

# __Conclusion__
This demo aims to illustrate the practical utility of Transformer models in real-world scenarios, emphasizing their effectiveness in understanding and generating human-like text.